# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import examples_service_pb2 as examples__service__pb2


class CalculatorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.add = channel.unary_unary(
        '/example_service.Calculator/add',
        request_serializer=examples__service__pb2.Numbers.SerializeToString,
        response_deserializer=examples__service__pb2.Result.FromString,
        )
    self.sub = channel.unary_unary(
        '/example_service.Calculator/sub',
        request_serializer=examples__service__pb2.Numbers.SerializeToString,
        response_deserializer=examples__service__pb2.Result.FromString,
        )
    self.mul = channel.unary_unary(
        '/example_service.Calculator/mul',
        request_serializer=examples__service__pb2.Numbers.SerializeToString,
        response_deserializer=examples__service__pb2.Result.FromString,
        )
    self.div = channel.unary_unary(
        '/example_service.Calculator/div',
        request_serializer=examples__service__pb2.Numbers.SerializeToString,
        response_deserializer=examples__service__pb2.Result.FromString,
        )


class CalculatorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def add(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sub(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def mul(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def div(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'add': grpc.unary_unary_rpc_method_handler(
          servicer.add,
          request_deserializer=examples__service__pb2.Numbers.FromString,
          response_serializer=examples__service__pb2.Result.SerializeToString,
      ),
      'sub': grpc.unary_unary_rpc_method_handler(
          servicer.sub,
          request_deserializer=examples__service__pb2.Numbers.FromString,
          response_serializer=examples__service__pb2.Result.SerializeToString,
      ),
      'mul': grpc.unary_unary_rpc_method_handler(
          servicer.mul,
          request_deserializer=examples__service__pb2.Numbers.FromString,
          response_serializer=examples__service__pb2.Result.SerializeToString,
      ),
      'div': grpc.unary_unary_rpc_method_handler(
          servicer.div,
          request_deserializer=examples__service__pb2.Numbers.FromString,
          response_serializer=examples__service__pb2.Result.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'example_service.Calculator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
